# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToanPhuc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Start.setGeometry(QtCore.QRect(120, 460, 211, 61))
        self.btn_Start.setObjectName("btn_Start")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(380, 460, 211, 61))
        self.btn_stop.setObjectName("btn_stop")
        self.lb_camera = QtWidgets.QLabel(self.centralwidget)
        self.lb_camera.setGeometry(QtCore.QRect(80, 10, 561, 381))
        self.lb_camera.setMaximumSize(QtCore.QSize(1920, 1080))
        self.lb_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_camera.setLineWidth(3)
        self.lb_camera.setText("")
        self.lb_camera.setScaledContents(True)
        self.lb_camera.setObjectName("lb_camera")
        self.txt_name = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(200, 400, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txt_name.setFont(font)
        self.txt_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_name.setTabChangesFocus(False)
        self.txt_name.setUndoRedoEnabled(True)
        self.txt_name.setAcceptRichText(True)
        self.txt_name.setObjectName("txt_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fruits Detecting"))
        self.btn_Start.setText(_translate("MainWindow", "Bắt đầu"))
        self.btn_stop.setText(_translate("MainWindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
